name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          sed 's/"//g' requirements.txt > requirements-ci.txt
          pip install -r requirements-ci.txt
          pip install black isort ruff pytest
          pip install -e .
      - name: Ruff
        run: ruff check .
      - name: Black
        run: black --check .
      - name: Isort
        run: isort --check .
      - name: Pytest
        run: pytest -q
